export const ImgData = [
  {
    id: 1,
    title: "The Mountains",
    author: "by Pixabay",
    date: "April 16th 2020",
    img: "/view/detail-pic/tatry-3954614_1280.jpg",
  },
  {
    id: 2,
    title: "Sunset Cityscapes",
    author: "by Pixabay",
    date: "April 14th 2020",
    img: "/view/detail-pic/sunset.webp",
  },
  {
    id: 3,
    title: "18 Days Voyage",
    author: "by Pixabay",
    date: "April 11th 2020",
    img: "/view/detail-pic/voyage.webp",
  },
  {
    id: 4,
    title: "Architecturals",
    author: "by Pixabay",
    date: "April 9th 2020",
    img: "/view/detail-pic/architect-1073607_1280.jpg",
  },
  {
    id: 5,
    title: "World Tour 2019",
    author: "by Pixabay",
    date: "April 7th 2020",
    img: "/view/detail-pic/vilnius-4229320_1280.jpg",
  },
  {
    id: 6,
    title: "Unforest Corners",
    author: "by Pixabay",
    date: "April 3rd 2020",
    img: "/view/detail-pic/natural-2411087_1280.jpg",
  },
  {
    id: 7,
    title: "King of Afeica: Part II",
    author: "by Pixabay",
    date: "March 29th 2020",
    img: "/view/detail-pic/lion-1118467_1280.jpg",
  },
  {
    id: 8,
    title: "The Trip Nowhere",
    author: "by Pixabay",
    date: "March 21st 2020",
    img: "/view/detail-pic/landscape-3119640_1280.jpg",
  },
  {
    id: 9,
    title: "Rage of The Sea",
    author: "by Pixabay",
    date: "March 19th 2020",
    img: "/view/detail-pic/sea-2300638_1280.jpg",
  },
  {
    id: 10,
    title: "Running Free",
    author: "by Pixabay",
    date: "March 16th 2020",
    img: "/view/detail-pic/horse-4720178_1280.jpg",
  },
  {
    id: 11,
    title: "Behind The Waves",
    author: "by Pixabay",
    date: "March 11th 2020",
    img: "/view/detail-pic/seagull-86318_1280.jpg",
  },
  {
    id: 12,
    title: "Calm Waters",
    author: "by Pixabay",
    date: "March 9th 2020",
    img: "/view/detail-pic/asia-2450659_1280.jpg",
  },
  {
    id: 13,
    title: "The Milkey Way",
    author: "by Pixabay",
    date: "March 5th 2020",
    img: "view/detail-pic/the-milky-way-3784335_1280.jpg",
  },
  {
    id: 14,
    title: "Night at The Dark Forest",
    author: "by Pixabay",
    date: "March 4th 2020",
    img: "/view/detail-pic/moutain-range-5830982_1280.jpg",
  },
  {
    id: 15,
    title: "Somwarpet's Beauty",
    author: "by Pixabay",
    date: "March 1st 2020",
    img: "/view/detail-pic/flower-2411080_1280.jpg",
  },
  {
    id: 16,
    title: "Land of Dreams",
    author: "by Pixabay",
    date: "February 25th 2020",
    img: "/view/detail-pic/winter-2385843_1280.jpg",
  },
];

export const Feature = [
  {
    id: 1,
    img: "/features/responsive.svg",
    title: "100% Responsive",
    des: "No matter which the device you’re on, our site is fully responsive and stories look beautiful on any screen.",
  },
  {
    id: 2,
    img: "/features/limit.svg",
    title: "No Photo Upload Limit",
    des: "Our tool has no limits on uploads or bandwidth. Freely upload in bulk and share all of your stories in one go.",
  },
  {
    id: 3,
    img: "/features/embed.svg",
    title: "Available to Embed",
    des: "Embed Tweets, Facebook posts, Instagram media, Vimeo or YouTube videos, Google Maps, and more.",
  },
  {
    id: 4,
    img: "/features/domain.svg",
    title: "Custom Domain",
    des: "With Photosnap subscriptions you can host your stories on your own domain. You can also remove our branding!",
  },
  {
    id: 5,
    img: "/features/exposure.svg",
    title: "Boost Your Exposure",
    des: "Users that viewed your story or gallery can easily get notifed of new and featured stories with our built in mailing list.",
  },
  {
    id: 6,
    img: "/features/image.svg",
    title: "Drag & Drop Image",
    des: "Easily drag and drop your image and get beautiful shots every time. No over the top tooling to add friction to creating stories.",
  },
];

export const Table = [
  {
    id: "1",
    title: "UNLIMITED STORY POSTING",
    basic: "/tick.png",
    pro: "/tick.png",
    business: "/tick.png",
  },
  {
    id: "2",
    title: "UNLIMITED PHOTO UPLOAD",
    basic: "/tick.png",
    pro: "/tick.png",
    business: "/tick.png",
  },
  {
    id: "3",
    title: "EMBEDDING CUSTOM CONTENT",
    basic: null,
    pro: "/tick.png",
    business: "/tick.png",
  },
  {
    id: "4",
    title: "CUSTOMIZE METADATA",
    basic: null,
    pro: null,
    business: "/tick.png",
  },
  {
    id: "5",
    title: "ADVANCED METRICS",
    basic: null,
    pro: null,
    business: "/tick.png",
  },
  {
    id: "6",
    title: "PHOTO DOWNLOADS",
    basic: null,
    pro: null,
    business: "/tick.png",
  },
  {
    id: "7",
    title: "SEARCH ENGINE INDEX",
    basic: null,
    pro: null,
    business: "/tick.png",
  },
  {
    id: "8",
    title: "CUSTOM ANALYTICS",
    basic: null,
    pro: null,
    business: "/tick.png",
  },
];
